Update log retention default
byu-oit/terraform-aws-fargate-api pull request #4
Opened 2020-07-08 20:59 UTC by romrell4

2020-07-08 21:01 UTC, yoshutch requested changes

2020-07-08 21:01 UTC, yoshutch commented on variables.tf
> +  default     = 30
Also update the inputs table in the README.md

2020-07-08 21:03 UTC, yoshutch requested changes
Oh and the version number of the module needs to be updated. (in the README and the examples)

2020-07-08 21:25 UTC, yoshutch submitted a review, later dismissed

2020-07-08 21:55 UTC, joshgubler submitted a review, later dismissed

2020-07-08 22:26 UTC, joshgubler approved these changes

2020-07-09 14:08 UTC, romrell4 reviewed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/byu-oit/terraform-aws-fargate-api/4)* status: all files reviewed, 1 unresolved discussion (waiting on @jvisker and @yoshutch)

___
*[variables.tf, line 164 at r1](https://reviewable.io/reviews/byu-oit/terraform-aws-fargate-api/4#-MBntp28eQIF74vVLeIG-r1-164:-MBntsUsAuMjk4Q0PKfs:b-896fix) ([raw file](https://github.com/byu-oit/terraform-aws-fargate-api/blob/2d4d1d2cc5fe489d66ef84f55a00527e1bae7781/variables.tf#L164)):*
<details><summary><i>Previously, yoshutch (Scott Hutchings) wrote…</i></summary><blockquote>

Also update the inputs table in the README.md
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-09 14:08 UTC, merged